version: '3.8'

services:
  # MariaDB Database (primary and only database)
  mariadb:
    image: mariadb:11
    container_name: financeflow_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-financeflow_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-financeflow}
      MYSQL_USER: ${MYSQL_USER:-financeflow_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-financeflow_password}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/mariadb-init:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    networks:
      - financeflow_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max-connections=100
      --query-cache-size=32M
      --query-cache-type=1

  # FinanceFlow Application
  financeflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financeflow_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=mysql://${MYSQL_USER:-financeflow_user}:${MYSQL_PASSWORD:-financeflow_password}@mariadb:3306/${MYSQL_DATABASE:-financeflow}
      - APP_SECRET=${APP_SECRET:-your_super_secret_key_change_this_in_production}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_change_this}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - UPLOAD_PATH=/app/uploads
      # AI API Keys (optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - financeflow_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backup service for MariaDB
  backup:
    image: mariadb:11
    container_name: financeflow_backup
    restart: "no"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-financeflow}
      MYSQL_USER: ${MYSQL_USER:-financeflow_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-financeflow_password}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backups:/backups
    networks:
      - financeflow_network
    command: |
      sh -c '
        while ! mysqladmin ping -h mariadb -u ${MYSQL_USER:-financeflow_user} -p${MYSQL_PASSWORD:-financeflow_password} --silent; do
          echo "Waiting for MariaDB..."
          sleep 2
        done
        echo "Creating backup..."
        mysqldump -h mariadb -u ${MYSQL_USER:-financeflow_user} -p${MYSQL_PASSWORD:-financeflow_password} ${MYSQL_DATABASE:-financeflow} > /backups/backup_$$(date +%Y%m%d_%H%M%S).sql
        echo "Backup completed!"
      '
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
    driver: local
  uploads_data:
    driver: local
  logs_data:
    driver: local

networks:
  financeflow_network:
    driver: bridge

# Unraid specific labels for better integration
x-unraid-labels:
  - "net.unraid.docker.managed=composeman"
  - "net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mariadb-icon.png"